### ISSUE TITLE
Unraid 7 needs updated user/group to work

### ISSUE THREAD

**Issue by Soitora** [mizz141/PlexAniSync-Mappings#149]
Hey!

I was having troubles on **Unraid 7 Beta 4** installing this, specifically the part regarding making the `custom_mappings.yaml` file

Turns out the solution for me was to add the `PUID` and `PGID` variables, to `99` and `100` respectivelly, which is the most common permissions on unraid containers (`nobody`/`users`), instead of throwing an error for "Bad parameter" it is now working without any errors.

Can also mention once the file was `touch`-ed in the Unraid terminal, I had to `chmod 775` and `chown nobody:users` to make it compatible. Which is weird because not changing `PUID`/`PGID` makes it run as `root` anyway, so I don't get why it happened

![image](https://github.com/user-attachments/assets/da07c25c-87a4-4b6b-8075-f08144e1798a)

**Comment by mizz141** [comment]
Hello,

Thanks for the Heads-up, i'll adjust these values in the template.

They won't work retroactively tho, only when the template is re-downloaded from the Apps section.

**Comment by mizz141** [comment]
Should be fixed now, hope it doesn't get nuked off of the App Store again
