### ISSUE TITLE
Can you please add entries for Urusei Yatsura (2022)?

### ISSUE THREAD

**Issue by MrGameVlogger** [mizz141/PlexAniSync-Mappings#63]
PlexAniSync is getting confused with [Urusei Yatsura (2022)](https://anilist.co/anime/143277/Urusei-Yatsura-2022/) as there is another anime with the same name from the 80s, and it's trying to match to that.

**Comment by mizz141** [comment]
@MrGameVlogger I've added a PR #64  which needs to be tested, I'm currently loading in the rest of the series to do that.

**Comment by mizz141** [comment]
Hello again, the commit works, but you have to manually rename the series for it to include the Year inside the title.

i.E for the 2022 series it would be Urusei Yatsura (2022) and the 1981 series, Urusei Yatsura (1981)

Else it would fail like you mentioned:
![image](https://user-images.githubusercontent.com/20839616/201479128-aa4c7245-b8f9-4694-9236-0e2a784df883.png)

**Comment by mizz141** [comment]
closed, issue has been (mostly) fixed.
